### ISSUE TITLE
Packaged x64 Angular Electron app produces javascript error: Cannot find module 'electron-edge-js'

### ISSUE THREAD

**Issue by tannerb1996** [agracio/electron-edge-js#138]
I'm able to successfully run an Angular project with electron-edge-js in dev; however, when packaging the app using electron-packager, the application fails to load and produces a JS error stating "Cannot find module 'electron-edge-js'". I've followed the edge-js documentation for setup and usage, with the below snippet's being my initialization (NOTE: this initialization is occurring in the electron main process):
`const edge = require('electron-edge-js');`

These are the dependencies referenced in the root packages.json file:
`"electron": "^17.4.9",
"electron-edge-js": "^17.0.0",
"electron-packager": "^15.5.1",`

Can someone please assist with some info on why this dependency may not be included properly on build? For reference, this is the build command for Windows apps that I've been using:
`npm run build --prod && cross-var electron-packager dist/my-app $npm_package_name-$npm_package_version --out=packages --platform=win32 --arch=all --overwrite`

EDIT FOR MORE INFO:
I'm also running node version 16.13.1, if that makes any sort of difference.

**Comment by agracio** [comment]
Did you check packaging sample and associated issues mentioned in redme?

**Comment by dbuldansjah** [comment]
For those who has problem with "The edge module has not been pre-compiled for Electron version 17.4.8" which is using webpack after publishing with electron-builder.
the steps that I resolve this problem are:

npm i electron-edge-js (the latest).
Configure webpack.config.js as such :
externals: {
'electron-edge-js': 'commonjs2 electron-edge-js',
},
Add extraResources as such: extraResources:[
"./node_modules/electron-edge-js/**",
],
on Main.js (electron) call the global:
require("module").globalPaths.push(process.cwd()+'/node_modules');
refer to: [https://github.com/ScottJMarshall/electron-webpack-module-resolution]
then:
var edge = require('electron-edge-js');

**Comment by agracio** [comment]
Take a look at [Packaging Electron application](https://github.com/agracio/electron-edge-js?tab=readme-ov-file#packaging-electron-application) in README it has examples for different application packagers including Webpack.

**Comment by AlekseyKurakin** [comment]
@agracio yep tried that, seems like now it has to be included by a plugin
```
plugins: [
  new webpack.LoaderOptionsPlugin({
    options: {
      extraResources:[
        "./node_modules/electron-edge-js/**",
      ]
    }
  })
],
```

![image (9)](https://github.com/user-attachments/assets/48e3d42d-3175-41ed-8bab-31d62f953143)

btw still didnt work for me. Now it tells that "cannot find module electron-edje-js"

**Comment by agracio** [comment]
What packager are you using?

**Comment by AlekseyKurakin** [comment]
Hey sorry for the delay, today i spend about 14hours total looking what i`m doing wrong.

I'm using webpack and was trying to connect to .net dll from my angular+electron.js project.
Everything was fine with running project as direct electron application, but when i tried to build it using electron-forge i start getting strange errors like "cannot find module electro-edje-js".

So i connected webpack config and applied examples from README file and for some reason it didnt work, but then i decided to run electron-edje-js in forked proccess and it worked (same as the example in README file: created a fork from main.js then applied my code in child.js file). 

Right now what i can see that module is working but i still cant call for my .net code because of error: "Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.". 
I believe that is something with EDGE_APP_ROOT env. Should it point to the directory where .dll and json files stored or directly to ,json file?

**Comment by agracio** [comment]
`Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.` usually means it is trying to run as .NET instead of .NET Core.
It is probably somehow ignoring `process.env.EDGE_USE_CORECLR = 1` or it was not passed properly

**Comment by AlekseyKurakin** [comment]
You are absolutely right. I didnt noticed that i put `process.env.EDGE_USE_CORECLR = 1` after `edge = require('electron-edge-js')` so that was the problem, now it working!
And thank you for electron-forge example it came just in time! My solution seems a bit off, so i will rebuild it

**Comment by dbuldansjah** [comment]
AlekseyKurakin, you can put the extraResource inside the package.json as
like this:

  "files": [
      "build/**/*",
      "node_modules/**/*",
      "package.json"
    ],
    "extraResources": [
      "node_modules/electron-edge-js/**"
    ],

**Comment by agracio** [comment]
There was an issue opened here: https://github.com/agracio/electron-edge-js-quick-start/issues/19 that is the reason for electron-forge example.
