### ISSUE TITLE
Building with Node.js v 10.2.0

### ISSUE THREAD

**Issue by gdavidkov** [agracio/electron-edge-js#22]
Hi,
 Is there an option to build a custom version with Node.Js 10.2.0?

Thanks!

**Comment by agracio** [comment]
I am assuming that this question belongs to https://github.com/agracio/edge-js/ repo because it would be meaningless to build a custom version of node for Electron.
Yes, you can build any version of node you want following build steps instruction on the original repo readme.
It is not clear why you would need a custom version though.

**Comment by gdavidkov** [comment]
Hi, thank you for your answer. I need it because the latest beta version of electron required it.
![image](https://user-images.githubusercontent.com/5815794/41896970-b020c1f4-792e-11e8-97ff-2e7fda43ade7.png)

**Comment by agracio** [comment]
I can see Electron 3.x beta was just released 5 days ago, I will try to include 10.2.0 in this repo in the next few days.

**Comment by gdavidkov** [comment]
Yes, you are right :) Thank you very much for your support.

**Comment by tpetrina** [comment]
Hi, any news on this?

**Comment by agracio** [comment]
Sorry, no luck yet. Hoping to be done by the end of the week.

**Comment by gdavidkov** [comment]
Hi, any progress?

**Comment by agracio** [comment]
Published in version 8.3.7
