### ISSUE TITLE
create winform from edge js will block electron ui

### ISSUE THREAD

**Issue by vjeson** [agracio/electron-edge-js#35]
new winform from edge js will block electron ui , you can't click anywhere except close the form

sample code 

`
var newForm = edge.func(`
        // eslint-disable-next-line no-unused-expressions

      #r "System.Windows.Forms.dll"
      using System.Windows.Forms;
      using System.Threading.Tasks;
      using System;
      public class Startup
      {
          public Task<object> Invoke(string command)
          {
            var tcs = new TaskCompletionSource<object>();
            var form = new Form();
            var button = new Button();
            var input = new TextBox();
            button.Text = "Hello World";
            button.Left = 100;
            button.Top = 100;
            input.Top = 100;
            form.Controls.Add(button);
            form.Controls.Add(input);
            button.Click += (x,y) => {
              var value = input.Text;
              form.Close();
              tcs.TrySetResult(value);
            };
            Application.Run(form);
            return tcs.Task;
          }
      }
`)

      newForm ('', function (error, result) {
        if (error) throw error
        console.log(result)
      })
`

**Comment by agracio** [comment]
Don't believe this behaviour is meant to be supported.

**Comment by vjeson** [comment]
It's useful for me, And I found a ugly way to achieve this. create a new hidden BrowserWindow in electron main process , new form in the new window , then it won't block the main process UI

**Comment by peter-sabath** [comment]
Sure this blocks because `Application.Run(form);` is a synchronous call and only returns after closing the last winform window.

I totally agree with agracio, but if you really need it you might give the following approach a try:

Use `form.Show()` on your form and have a periodic javascript function (e.g. a setTimer()) that calls `Application.ProcessMessages()` on the C# side to run the windows forms message loop.
