### ISSUE TITLE
I use electron v3.0.10 and node.js v10.2.0 and electron-edge-js have a problem about edge_nativeclr

### ISSUE THREAD

**Issue by zxy-mapper** [agracio/electron-edge-js#39]
![image](https://user-images.githubusercontent.com/25167637/53390677-d9b3db80-39ce-11e9-887c-224b4374f4ed.png)

this is my code
![image](https://user-images.githubusercontent.com/25167637/53394861-741a1c00-39db-11e9-806f-d209a909221d.png)

![image](https://user-images.githubusercontent.com/25167637/53394983-b93e4e00-39db-11e9-91ec-4bd14d123363.png)

I hope to get your help 

thanks

**Comment by QBIRGAENTZLE** [comment]
I have the same issue under Node 10.11 and Electron 4.0.5. I just installed electron-edge-js and tried to do a "Hello World" test (about the same as OP) and got exactly the same error

**Comment by tbeswick96** [comment]
Similar issue running Electron 4.1.1, Node 10.15.3, and Angular 7
Error I get is:
```
Cannot find module Uncaught Error: Cannot find module '....\App\node_modules\electron\dist\resources\electron.asar\renderer\native\win32\x64\10.11.0\edge_nativeclr'
    at webpackEmptyContext (lib sync:2)
    at Object../node_modules/electron-edge-js/lib/edge.js (edge.js:59)
    at __webpack_require__ (bootstrap:78)
    at Module../src/app/pages/home/home.component.ts (main.js:4027)
    at __webpack_require__ (bootstrap:78)
    at Module../src/app/app-routing.module.ts (main.js:3447)
    at __webpack_require__ (bootstrap:78)
    at Module../src/app/app.module.ts (app.component.ts:15)
    at __webpack_require__ (bootstrap:78)
    at Module../src/main.ts (main.ts:1)
```

I'm using angular as well, and I think in my case it might have something to do with that.
I can run the sample repo fine, using the same versions as above.
I can run my own app fine if I run it with `electron .` but the angular stuff doesn't load.
However if I run it so the angular stuff does load, I get the above error, presumably because the edge files haven't been built to the right place?

My package.json file for reference: https://gist.github.com/tbeswick96/798a5d07bfede1197b65d097ed0b4e95

**Comment by Hammster** [comment]
You need to prevent electron-edje-js from beein packed into the .asar file, you cannot load native node modules from it.

@tbeswick96 config for example he uses `electron-builder` so he need to exclude electron-edje-js from the asar packing by defining the `asarUnpack` config https://www.electron.build/configuration/configuration#Configuration-asar

**Comment by tbeswick96** [comment]
@Hammster Added `"asarUnpack": "*.+(node|dll)"` to my electron-builder.json, but still the same error.
This occurs when I am not packing it with electron-builder, i.e running locally for development
I haven't tried making a release build as it needs to work in development first

**Comment by agracio** [comment]
Take a look at this example for packaging Electron with `electron-edge-js`: https://github.com/zenb/electron-edge-js-quick-start. This is based of original quickstart provided for this repo: https://github.com/agracio/electron-edge-js-quick-start

**Comment by tbeswick96** [comment]
That's useful, thanks, but that doesn't help the main issue which is running this with angular.
I'm trying to run an electron-builder build, i'm running it locally with npm start, and I get the error.
The edge part works when I run `npm run electron .` but I get none of the angular interface
The angular interface works when I run `npm start`, but I get the edge error

**Comment by agracio** [comment]
It depends what `npm start` does in your project, as you can see from error message it is trying to find  parts of `electron-edge-js` inside asar archive. You need to figure out what is executed when you run `npm start` and what needs to be done to make it work for both Angular and electron-edge-js.

**Comment by tbeswick96** [comment]
I have managed to get it working. Managed to find a working example out there that had all three components (electron, angular, and edge) and copied how it laid things out.
For reference: https://github.com/bill-long/EventLogExpert
It works both running locally, and packaged with electron-builder

I think the error message I was getting was misleading, as I think it was actually my own dll location that was failing. Not certain

@ApologizeAndStruggle @QBIRGAENTZLE I'd recommend trying to find an existing application out there with a similar setup to yours, and then copy the essential bits from that (like package.json) and see if that helps

**Comment by mbsg** [comment]
I have the same problem
`Error: Cannot find module 'project_root\dist_electron\native\win32\x64\12.4.0\edge_nativeclr'`
Electron v6.1.0
Node v12.4.0
vue/cli 4.0.4
windows 10 1903 x64

**Comment by tritrancs** [comment]
I have the same issue:
![image](https://user-images.githubusercontent.com/750334/69476075-b310bd00-0e07-11ea-8a3c-6a9fb260364f.png)
Electron v6.1.5
Node v12.4.0
vue/cli 4.0.5
electron-edge-js v12.4.1
windows 10 x64.
The error occurs when I require the electron-edge-js module.
` var edge = require('electron-edge-js');`

**Comment by david1025** [comment]
> I have the same issue:
> ![image](https://user-images.githubusercontent.com/750334/69476075-b310bd00-0e07-11ea-8a3c-6a9fb260364f.png)
> Electron v6.1.5
> Node v12.4.0
> vue/cli 4.0.5
> electron-edge-js v12.4.1
> windows 10 x64.
> The error occurs when I require the electron-edge-js module.
> ` var edge = require('electron-edge-js');`
> Note: This happens in development, not packaging.

the same question,I will be carzy

**Comment by lesleyandreza** [comment]
Hey, guys.
I had the same problem.
I decided to add extra parameters in the webpack configuration for the rendering process and it worked for me:
```javascript
...
  externals: {
    'electron-edge-js': 'commonjs2 electron-edge-js',
  },
  node: {
    __dirname: false,
    __filename: false,
  },
...
```
To clear up my doubts, I ran the electro-quick-start project without a webpack and it worked, so I researched a configuration to discard the `electron-edge-js` of the build process.
In my case the bad configured webpack that generated this bug.

**Comment by akozhemiakin** [comment]
@lesleyandreza 
I'm a little bit confused, is it a question to me or to someone I should have helped?) If it is a question to me, would you mind to clarify it a little bit)

**Comment by lesleyandreza** [comment]
Sorry @akozhemiakin.
I wish I had marked the creator of this issue @zxy-mapper.

**Comment by nuryagdym** [comment]
We also have the same problem, on one of our customer device. 
Although we tested our app both on Windows 10 and 7 (32bit), on the customers device we are getting this error.
The path of `edge_nativeclr.node` on error message is correct, it does exist. but I can't figure out the reason of the error.
installing Microsoft Visual C++ Redistributable 2015 (x86) does not solve issue.

**Comment by joseypan** [comment]
I have the same quesition,when i use the electron 11,node 12.18.3,electron-edge-js 12.18.5
I read the document about 'electron-edge-js'，it supported the version i use
maybe this quesition was caused by webpack compile,but i use 'vue-cli-plugin-eletron-builder' with the externals attribute, also wrong
who has some suggests form me? thanks a lot
![image](https://user-images.githubusercontent.com/68236258/113094180-d03b7400-9223-11eb-8a56-2d0287a12308.png)

**Comment by david1025** [comment]
你咱们qq沟通吧，我远程给你看看，我这儿跑了一下没啥问题



----------------------------

Best Regards

David Zhang&nbsp;张大伟

Tel &nbsp; &nbsp;：15620976885

***@***.***
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ***@***.***
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ***@***.***
QQ &nbsp; ：990860210



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "agracio/electron-edge-js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月31日(星期三) 中午1:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [agracio/electron-edge-js] I use electron v3.0.10 and node.js v10.2.0 and electron-edge-js have a problem about edge_nativeclr (#39)





 
I have the same quesition,when i use the electron 11,node 12.18.3,electron-edge-js 12.18.5
 I read the document about 'electron-edge-js'，it supported the version i use
 maybe this quesition was caused by webpack compile,but i use 'vue-cli-plugin-eletron-builder' with the externals attribute, also wrong
 who has some suggests form me? thanks a lot
