### ISSUE TITLE
webpack warning: "Critical dependency: the request of a dependency is an expression"

### ISSUE THREAD

**Issue by aispark** [agracio/electron-edge-js#48]
Environments:

"electron-edge-js": "^12.0.1",
"electron": "^5.0.6",
"vue-cli-plugin-electron-builder": "^1.3.4",

Running:, vue-cli
Runtime: Node v10.16.1
Operating System: windows 64bit
Steps to reproduce:

vue-cli-service electron:serve --mode development

![20190804_131543](https://user-images.githubusercontent.com/5924872/62419408-45a31a00-b6ba-11e9-86b2-a2aeb891f1c7.png)

**Comment by Hammster** [comment]
This can be ignored, since in edge it is about the built `.node` files. so nothing will get bundled as a duplicate.

https://github.com/agracio/electron-edge-js/blob/2903ae0343c4acef2492b89dc735fc49cfb2bfcb/lib/edge.js#L3

https://github.com/agracio/electron-edge-js/blob/2903ae0343c4acef2492b89dc735fc49cfb2bfcb/lib/edge.js#L39

https://github.com/agracio/electron-edge-js/blob/2903ae0343c4acef2492b89dc735fc49cfb2bfcb/lib/edge.js#L101-L105

**Comment by aispark** [comment]
thank you
