### ISSUE TITLE
Can we force load .NET 4.7.2? ...Net 4.5.2 has security issue where TLS 1.0 is used

### ISSUE THREAD

**Issue by dmcgloin** [agracio/electron-edge-js#56]
We've noticed that our Electron app appears to be loading .NET 4.5.2 which is causing our HTTP connections to use TLS 1.0.

Our understanding from experimentation and reading this article:

   https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls

... is that .Net 4.7.2 and newer "do the right thing", meaning the connections are established using the newest protocol supported by the server, in our case, TLS 1.2 or 1.3

We are using Electron v 1.7.9 with Node 8.16.
electron-edge-js version is 12.0.1

Is there some sort of configuration that would allow us to force using .NET 4.7.2?

Or, more specifically, is there any way to ensure HTTP connections use TLS 1.2 or newer?

Thanks very much! Any guidance is appreciated.

**Comment by peter-sabath** [comment]
You have two ways to accomplish your goal.

first is to add an `Electron.exe.config` to your directory that contains the `Electron.exe` (or the name your Electron app was renamed to)

or, and that is just my favorite if you do not really need new APIs of 4.7.2, just add single-line of code:

```ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;```

This enforces TLS 1.2 only. You might add ` | SecurityProtocolType.Tls13` to the line above to also allow TLS 1.3

Don't use or leave the SecurityProtocolType.SystemDefault set, because most systems allow the older ones and the preferences of the .NET framework are "not the best".
