### ISSUE TITLE
Cannot use it independently

### ISSUE THREAD

**Issue by c445352742** [agracio/electron-edge-js#6]
It's your feature or bug?

I can use it well in electron, but something happend when I run `node dotnet.js`
Here is the report
```
return edge.initializeClrFunc(options);
               ^

TypeError: Cannot read property 'initializeClrFunc' of unde
fined
    at Object.exports.func (E:\github\ElectronWithDll-ATM\n
ode_modules\electron-edge-js\lib\edge.js:181:16)
```
source code is the demo from edgejs docs
```
const edge=require('electron-edge-js');

var hello = edge.func(function () {/*
 async (input) => {
 return "CSharp welcomes " + input.ToString();
 }
 */});

hello('Node.js', function (error, result) {
  if (error) throw error;
  console.log(result);
});

```
On windows7x64 phpstrom, nodejs v8.2.1

**Comment by agracio** [comment]
This is by design. `electron-edge-js` can only be used inside Electron app because the module is compiled not only to use the same Node.js version as Electron but also uses special compile options to support custom node.dll that ships with Electron. For regular Node.js apps use `edge-js` https://github.com/agracio/edge-js.

**Comment by c445352742** [comment]
Ok,thank you very much.
